name: Тесты (shop/tests)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Установка Django
        run: |
          python -m pip install --upgrade pip
          pip install Django coverage

      - name: Запуск только тестов из shop/tests/
        run: |
          python manage.py test shop.tests --verbosity=2 --keepdb

      - name: Покрытие кода
        run: |
          coverage run --source=shop manage.py test shop.tests
          coverage report -m